modLoader="javafml"
loaderVersion="[33,)"
license="GNU General Public License v3.0"
issueTrackerURL="https://github.com/AndrewBrooking/Chopper/issues"

[[mods]]
	modId="chopper"
	version="${version}"
	displayName="Chopper"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/chopper"
	credits="Thanks to Mojang, the Forge team, and progwml6 for his IronChests mod as a reference"
	logoFile="chopper_icon.png"
	authors="cer0tech"
	description='''
Chest + Hopper = Chopper
	'''
	[[dependencies.chopper]]
	    modId="forge"
	    mandatory=true
	    versionRange="[${forge_version},)"
	    ordering="NONE"
	    side="BOTH"
