modLoader="javafml"
loaderVersion="[33,)"
license="GNU General Public License v3.0"
issueTrackerURL="https://github.com/AndrewBrooking/Chopper/issues"

[[mods]]
	modId="chopper"
	version="1.0.1"
	displayName="Chopper"
	displayURL="https://github.com/AndrewBrooking/Chopper"
	credits="Thanks to Mojang, the Forge team, and progwml6 for his IronChests mod as a reference"
	authors="cer0tech"
	description='''
Chest + Hopper = Chopper
	'''
	[[dependencies.chopper]]
	    modId="forge"
	    mandatory=true
	    versionRange="[33,)"
	    ordering="NONE"
	    side="BOTH"
